<div class="bg-write">
    <a href="" class="btn btn-warning" data-toggle="modal" data-target="#modal-filtros">Filrar Partidas</a>
    <a href="<?php echo $this->url(array(
        'controller' => 'index',
        'action' => 'index'
    ), null, true); ?>" class="text-danger"><i class="fa fa-times"></i> Limpar Filtros</a>
</div>

<!-- MODAL DE APOSTA -->
<div class="modal fade" id="modal-filtros" data-backdrop="static" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">FILTROS</h4>
            </div>
            <div class="modal-body">
                <?php echo $this->formFiltrosPartida; ?>
            </div>                            
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>