<section>    
    <div class="row">
        <!-- SIDE BAR -->
        <div class="col-md-3">            
            <?php if (Plugin_Auth::check()) : ?>
            <div class="panel panel-info">
                <div class="panel-heading">Minha Conta</div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-3">
                            <img src="<?php echo $this->baseUrl('views/img/user/' . Zend_Auth::getInstance()->getIdentity()->usuario_avatar); ?>" class="img center-block" width="50" />
                        </div>
                        <div class="col-md-9 text-center">
                            <label>
                                <h4><?php echo Zend_Auth::getInstance()->getIdentity()->usuario_nome; ?></h4>
                            </label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 site-menu">
                            <a href="<?php echo $this->url(array(
                                "controller" => "usuario", 
                                "action" => "index"
                            ), null, true); ?>"><p><i class="fa fa-user"></i> Minha Conta</p></a>
                            <a href="" data-toggle="modal" data-target="#modal-notificacao">
                                <p>
                                    <i class="fa fa-bell"></i> Notificações 
                                    <?php if ($this->notificacoes->count() > 0) : ?>
                                    <span class="badge"><?php echo $this->notificacoes->count(); ?></span>
                                    <?php endif; ?>
                                </p>
                            </a>
                            <a href="<?php echo $this->url(array(
                                "controller" => "auth", 
                                "action" => "logout"
                            )); ?>"><p><i class="fa fa-sign-out"></i> Sair</p></a>                                
                        </div>
                    </div>
                    <!-- MODAL DE APOSTA -->
                    <div class="modal fade" id="modal-notificacao" tabindex="-1" role="dialog">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                    <h4 class="modal-title">Notificações</h4>
                                    <p class="small text-muted">
                                        Clique no botão <span class="btn btn-sm btn-primary"><i class="fa fa-thumbs-up"></i> OK</span>
                                        para marcar como lida
                                    </p>
                                </div>
                                <div class="modal-body">
                                    <?php if ($this->notificacoes->count() > 0) : ?>
                                    <div class="row">
                                        <div class="col-md-12 text-right">
                                            <a href="<?php echo $this->url(array(
                                                'controller' => 'notificacao',
                                                'action' => 'todas-lidas'
                                            ), null, true); ?>" class="btn btn-sm btn-info">Marcar todas como lida</a>
                                        </div>
                                    </div>                                    
                                    <?php foreach ($this->notificacoes as $notificacao) : ?>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="thumbnail">
                                            <p>
                                                <?php echo $notificacao->notificacao_conteudo; ?>
                                            </p>
                                            <p class="text-right">
                                                <a class="btn btn-sm btn-primary" href="#" id="">
                                                    <i class="fa fa-thumbs-up"> OK</i>
                                                </a>
                                            </p>
                                            </div>
                                        </div>
                                    </div>
                                    <?php endforeach; ?>
                                    <?php else : ?>
                                    <div class="alert alert-warning">Nenhuma notificação</div>
                                    <?php endif; ?>
                                </div>                            
                            </div><!-- /.modal-content -->
                        </div><!-- /.modal-dialog -->
                    </div><!-- /.modal -->
                </div>
            </div>
            <div class="panel panel-info">
                <div class="panel-heading">Saldo</div>
                <div class="panel-body">
                    <h1 class="text-center text-success"><b><?php echo $this->currency($this->saldo); ?></b></h1>
                    <p class="small text-center">
                        <a href="" data-toggle="modal" data-target="#modal-extrato">Ver Extrato</a>
                    </p>
                    
                    <!-- EMPRESTIMO -->
                    <?php if ($this->saldo <= Zend_Registry::get('config')->emprestimo->saldo->minimo) : ?>
                    <a href="<?php echo $this->url(array(
                        'controller' => 'emprestimo',
                        'action' => 'index'
                    ), null, true); ?>" class="btn btn-warning btn-block"><i class="fa fa-money"></i> EMPRÉSTIMO
                        <label class="label label-success small">Novo</label>
                    </a>
                    <?php endif; ?>
                    
                    <!-- DEPOSITO -->
                    <a href="<?php echo $this->url(array(
                        'controller' => 'deposito',
                        'action' => 'index'
                    ), null, true); ?>" class="btn btn-primary btn-block"><i class="fa fa-money"></i> DEPOSITAR</a>
                    
                    <!-- RESGATE -->                    
                    <?php if ($this->saldo_resgate >= Zend_Registry::get("config")->resgate->minimo) : ?>
                    <a href="<?php echo $this->url(array(
                        'controller' => 'resgate',
                        'action' => 'index'
                    ), null, true); ?>" class="btn btn-info btn-block"><i class="fa fa-money"></i> RESGATAR</a>
                    <?php else : ?>
                    <a href="#" disabled class="btn btn-danger btn-block"><i class="fa fa-money"></i> RESGATAR*</a>
                    <p class="small text-muted">* Saldo mínimo: <?php echo $this->currency(Zend_Registry::get("config")->resgate->minimo); ?> em premiação</p>
                    <?php endif; ?>
                    
                    <!-- MODAL DE APOSTA -->
                    <div class="modal fade" id="modal-extrato" tabindex="-1" role="dialog">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                    <h4 class="modal-title">EXTRATO</h4>
                                </div>
                                <div class="modal-body">
                                    <h4 class="text-success text-right">Saldo Atual: <?php echo $this->currency($this->saldo); ?></h4>
                                    <table class="table table-bordered">
                                        <tr>
                                            <th>Data</th>
                                            <th>Descrição</th>
                                            <th>Crédito</th>
                                            <th>Débito</th>
                                        </tr>
                                        <?php foreach ($this->lancamentos as $lancamento) : ?>
                                        <tr>
                                            <td class="text-center"><?php echo App_Helper_Date::getDateView($lancamento->lancamento_data); ?></td>
                                            <td><?php echo $lancamento->lancamento_descricao; ?></td>
                                            <td class="text-success text-right">
                                                <?php echo $lancamento->lancamento_valor > 0 ? $this->currency($lancamento->lancamento_valor) : ''; ?>
                                            </td>
                                            <td class="text-danger text-right">
                                                <?php echo $lancamento->lancamento_valor < 0 ? $this->currency($lancamento->lancamento_valor) : ''; ?>
                                            </td>
                                        </tr>
                                        <?php endforeach; ?>
                                    </table>
                                </div>                            
                            </div><!-- /.modal-content -->
                        </div><!-- /.modal-dialog -->
                    </div><!-- /.modal -->
                </div>
            </div>
            <div class="panel panel-info">
                <div class="panel-heading">                    
                    Minhas Apostas
                    <span class="badge"><?php echo $this->apostas->count(); ?></span>
                </div>
                <div class="panel-body">
                <?php if ($this->apostas->count() > 0) : ?>
                    <?php foreach ($this->apostas as $aposta) : ?>
                    <table class="table">
                        <tr class="text-center">
                            <td><img src="<?php echo $this->baseUrl('views/img/times/' . $aposta->time_escudo_mandante); ?>" class="img center-block" width="50" /></td>
                            <td><?php echo $aposta->aposta_placar_mandante; ?></td>
                            <td>X</td>
                            <td><?php echo $aposta->aposta_placar_visitante; ?></td>
                            <td><img src="<?php echo $this->baseUrl('views/img/times/' . $aposta->time_escudo_visitante); ?>" class="img center-block" width="50" /></td>
                        </tr>
                        <tr class="text-center">
                            <td colspan="5">
                                <a href="#" data-toggle="modal" data-target="#modal-aposta-editar-<?php echo $aposta->aposta_id; ?>" class="btn btn-sm btn-info">
                                    <i class="fa fa-edit"></i> Alterar
                                </a>                            
                                <a href="<?php echo $this->url(array(
                                    'controller' => 'aposta',
                                    'action' => 'delete',
                                    'id' => $aposta->aposta_id
                                ), null, true); ?>" class="btn btn-sm btn-danger">
                                    <i class="fa fa-trash"></i> Cancelar
                                </a>
                            </td>
                        </tr>
                    </table><hr />
                    
                    <!-- MODAL DE APOSTA EDITAR-->
                    <div class="modal fade" id="modal-aposta-editar-<?php echo $aposta->aposta_id; ?>" data-backdrop="static" tabindex="-1" role="dialog">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                    <h4 class="modal-title">EDITAR APOSTA</h4>
                                </div>
                                <div class="modal-body">                                    
                                    <p>Informe o placar da partida e torça para sua aposta ser a vencedora!</p>  
                                    <?php $this->formApostarAlterar->setAction("aposta/alterar"); ?>
                                    <form method="<?php echo $this->formApostarAlterar->getMethod(); ?>" action="<?php echo $this->formApostarAlterar->getAction(); ?>">
                                        <table class="table">
                                            <tr class="text-center">
                                                <td class="col-md-3">
                                                    <img src="<?php echo $this->baseUrl('views/img/times/' . $aposta->time_escudo_mandante); ?>" class="img center-block" />
                                                </td>                                            
                                                <td class="col-md-2">
                                                    <?php $this->formApostarAlterar->aposta_placar_mandante->setValue($aposta->aposta_placar_mandante); ?>
                                                    <?php echo $this->formApostarAlterar->aposta_placar_mandante; ?>
                                                </td>
                                                <td class="col-md-2">X</td>
                                                <td class="col-md-2">
                                                    <?php $this->formApostarAlterar->aposta_placar_visitante->setValue($aposta->aposta_placar_visitante); ?>
                                                    <?php echo $this->formApostarAlterar->aposta_placar_visitante; ?>
                                                </td>                                            
                                                <td class="col-md-3">
                                                    <img src="<?php echo $this->baseUrl('views/img/times/' . $aposta->time_escudo_visitante); ?>" class="img center-block" />
                                                </td>                            
                                            </tr>
                                            <tr>
                                                <?php $this->formApostarAlterar->aposta_id->setValue($aposta->aposta_id); ?>
                                                <?php echo $this->formApostarAlterar->aposta_id; ?>
                                                <td colspan="5"><?php echo $this->formApostarAlterar->submit; ?></td>
                                                <?php 

                                                    $this->formApostar->partida_id->setValue($aposta->partida_id);                                                
                                                    $this->formApostar->usuario_id->setValue(Zend_Auth::getInstance()->getIdentity()->usuario_id);
                                                    //$this->formApostar->usuario_id->setValue(1);                                               

                                                    echo $this->formApostar->partida_id;
                                                    echo $this->formApostar->usuario_id;

                                                ?>
                                            </tr>
                                        </table>
                                    </form>
                                </div>                            
                            </div><!-- /.modal-content -->
                        </div><!-- /.modal-dialog -->
                    </div><!-- /.modal -->
                    <?php endforeach; ?>
                <?php else : ?>
                    <div class="alert alert-warning">Nenhuma aposta realizada</div>
                <?php endif; ?>
                </div>
            </div>
            <?php else : ?>
            <div class="panel panel-info">
                <div class="panel-heading">Acesse sua conta</div>
                <div class="panel-body">
                    <?php echo $this->formLogin; ?>
                    <p>
                        <a href="<?php echo $this->url(array("controller" => "auth", "action" => "esqueci")); ?>">Esqueci a senha</a>
                    </p>
                </div>
            </div>
            <div class="panel panel-info">
                <div class="panel-heading">Cadastre-se grátis</div>
                <div class="panel-body text-center">
                    <?php if (Zend_Registry::get("config")->bonus->cadastro > 0) : ?>
                    <p>
                        <label>Faça seu cadastro e ganhe</label> 
                        <h2><?php echo $this->currency(Zend_Registry::get("config")->bonus->cadastro); ?> de BÔNUS</h2>
                    </p>
                    <?php else : ?>
                    <p>
                        <label>
                            Faça seu cadastro <span class="bolder text-danger">GRÁTIS</span>.
                            É rápidinho!!!
                        </label>
                        
                    </p>
                    <?php endif; ?>
                    <p>
                        <a href="<?php echo $this->url(array("controller" => "cadastro", "action" => "index")); ?>" class="btn btn-primary">CADASTRAR</a>
                    </p>
                </div>
            </div>
            <?php endif; ?>
        </div>
        
        <!-- PARTIDAS -->
        <div class="col-md-9">            
            <?php if ($this->partidas->count() > 0) : ?>            
                <?php foreach ($this->partidas as $partida) : ?>                
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="row">                            
                            <div class="col-lg-8 col-sm-8 col-md-8 col-xs-12 text-center" style="border-right: 1px solid #3c763d">                                
                                <div class="row">
                                    <div class="col-lg-12">
                                        <label>
                                            <?php echo $this->serie($partida->partida_serie); ?> - 
                                            <?php echo $partida->partida_rodada; ?>ª Rodada -
                                            <?php echo App_Helper_Date::getDate($partida->partida_data, Zend_Date::DATETIME_SHORT); ?>h
                                        </label>

                                        <div class="table-responsive">
                                            <table class="table">
                                                <tr class="text-center">
                                                    <td class="col-md-2">
                                                        <img src="<?php echo $this->baseUrl('views/img/times/' . $partida->time_mandante_escudo); ?>" class="img center-block" />
                                                    </td>
                                                    <td class="col-md-3" id="time_mandante_nome" style="font-size: 20px;"><b><?php echo $partida->time_mandante_nome; ?></b></td>
                                                    <td class="col-md-2" style="font-size: 20px;"><b>X</b></td>
                                                    <td class="col-md-3" id="time_visitante_nome" style="font-size: 20px;"><b><?php echo $partida->time_visitante_nome; ?></b></td>
                                                    <td class="col-md-2">
                                                        <img src="<?php echo $this->baseUrl('views/img/times/' . $partida->time_visitante_escudo); ?>" class="img center-block" />
                                                    </td>                            
                                                </tr>
                                            </table>
                                        </div>
                                    </div>
                                </div>                                
                                <div class="row" id="buttom-apostar-desktop">                         
                                    <?php if (Plugin_Auth::check()) : ?>                                                                
                                    <div class="col-lg-8 col-lg-offset-2" style="margin-bottom: 10px;">
                                        <p class="small"><?php echo $this->apostas($partida->partida_id); ?></p>
                                        <a href="" class="btn btn-lg btn-primary btn-block" data-toggle="modal" data-target="#modal-aposta-<?php echo $partida->partida_id; ?>">APOSTAR</a>
                                    </div>
                                    <?php else : ?>
                                    <div class="col-lg-12 text-center">
                                        <p class="text-info">Faça o login ou se cadastre para apostar nesta partida</p>
                                    </div>
                                    <?php endif; ?>
                                </div>  
                            </div>                             
                            <div class="col-lg-4 col-sm-4 col-md-4 col-xs-12 text-center">
                                <div class=" <?php echo $partida->partida_coringa_valor > 1 ? 'bg-success' : ''; ?>" style="padding: 15px;">
                                    <h4 class="text-success bolder">PRÊMIO</h4>
                                    <h1>
                                        <span class="text-info">                                                                             
                                            <?php echo $this->currency($this->montante($partida->partida_id)); ?>*
                                        </span>
                                    </h1>
                                    <p>
                                        <span class="text-center small bolder">Valor da aposta: <?php echo $this->currency($partida->partida_valor); ?></span>
                                    </p>
                                    <p class="small text-muted">                                        
                                        * Valor do 1ª prêmio. Apostas computadas até o presente momento.
                                        <?php if ($partida->partida_coringa_valor > 1) : ?>                                                                                                                  
                                        Aposta coringa: prêmio multiplicado <?php echo $partida->partida_coringa_valor; ?>X 
                                        <?php endif; ?>   
                                        
                                    </p>
                                    <!--
                                    <p>
                                        <a href="" class="btn btn-block btn-warning">
                                            <i class="fa fa-bar-chart"></i> Estatísticas
                                        </a>
                                    </p>
                                    -->
                                </div>  
                            </div>
                            
                        </div>
                        
                        <div class="row" id="buttom-apostar-mobile">                         
                            <?php if (Plugin_Auth::check()) : ?>                                                                
                            <div class="col-lg-8 col-lg-offset-2" style="margin-bottom: 10px;">
                                <p class="small"><?php echo $this->apostas($partida->partida_id); ?></p>
                                <a href="" class="btn btn-lg btn-primary btn-block" data-toggle="modal" data-target="#modal-aposta-<?php echo $partida->partida_id; ?>">APOSTAR</a>
                            </div>
                            <?php else : ?>
                            <div class="col-lg-12 text-center">
                                <p class="text-info">Faça o login ou se cadastre para apostar nesta partida</p>
                            </div>
                            <?php endif; ?>
                        </div>  
                        
                    </div>                    
                </div> 
            
                <!-- MODAL DE APOSTA -->
                <div class="modal fade" id="modal-aposta-<?php echo $partida->partida_id; ?>" data-backdrop="static" tabindex="-1" role="dialog">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                <h4 class="modal-title">APOSTAR</h4>
                            </div>
                            <div class="modal-body">
                                <?php if ($this->saldo >= $partida->partida_valor) : ?>
                                <p>Informe o placar da partida e torça para sua aposta ser a vencedora!</p>
                                <h5 class="bolder">Valor da aposta: <?php echo $this->currency($partida->partida_valor); ?></h5>   
                                <form method="<?php echo $this->formApostar->getMethod(); ?>" action="<?php echo $this->formApostar->getAction(); ?>">
                                    <table class="table">
                                        <tr class="text-center">
                                            <td class="col-md-3">
                                                <img src="<?php echo $this->baseUrl('views/img/times/' . $partida->time_mandante_escudo); ?>" class="img center-block" />
                                            </td>                                            
                                            <td class="col-md-2">
                                                
                                                <?php echo $this->formApostar->aposta_placar_mandante; ?>
                                            </td>
                                            <td class="col-md-2">X</td>
                                            <td class="col-md-2">
                                                <?php echo $this->formApostar->aposta_placar_visitante; ?>
                                            </td>                                            
                                            <td class="col-md-3">
                                                <img src="<?php echo $this->baseUrl('views/img/times/' . $partida->time_visitante_escudo); ?>" class="img center-block" />
                                            </td>                            
                                        </tr>
                                        <tr>
                                            <td colspan="5"><?php echo $this->formApostar->submit; ?></td>
                                            <?php 
                                                
                                                $this->formApostar->partida_id->setValue($partida->partida_id);                                                
                                                $this->formApostar->usuario_id->setValue(Zend_Auth::getInstance()->getIdentity()->usuario_id);
                                                //$this->formApostar->usuario_id->setValue(1);                                               
                                                                                                
                                                echo $this->formApostar->partida_id;
                                                echo $this->formApostar->usuario_id;
                                            
                                            ?>
                                        </tr>
                                    </table>
                                </form>
                                
                                <!-- APOSTAS REALIZADAS PELO USUARIO NA PARTIDA -->
                                <?php echo $this->apostas($partida->partida_id, 'label'); ?>
                                
                                <?php else : ?>
                                <div class="alert alert-danger">
                                    Desculpe, você não tem saldo suficiente para
                                    apostar nesta partida.                                    
                                </div>
                                <hr />
                                <p>Faça um depósito para continuar suas apostas.</p>
                                <a href="<?php echo $this->url(array(
                                    'controller' => 'deposito',
                                    'action' => 'index'
                                ), null, true); ?>" class="btn btn-primary">DEPOSITAR</a>
                                <?php endif; ?>
                            </div>                            
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                </div><!-- /.modal -->
                <?php endforeach; ?>            
            <?php else : ?>
                <div class="alert alert-warning">No momento ainda não temos nenhuma partida para apostar. Por favor aguarde!</div>
            <?php endif; ?>
        </div>
        
    </div>
</section>
