<style>
    h1 {
        font-size: 60px;
        color: #122b40;        
        font-weight: bold;
    }
    
    h2 {
        font-size: 40px;
        color: #255625;
        font-weight: bold;
    }
    
    h4 {
        font-size: 27px;
        color: #255625;
        font-weight: bold;
    }
    
    h5 {
        font-size: 18px;
        color: #255625;
        font-weight: bold;
    }
    
    .panel-body {
        font-weight: bold;
    }
    
    .total {
        font-size: 20px;
        text-align: center;
    }
    
</style>
<section>
    <div class="row">
        <div class="col-md-12">
            <h3>Dashboard</h3><hr />
        </div>
    </div>    
    <div class="row">
        
        <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
        
            <div class="row">
                <!-- APOSTAS -->
                <div class="col-xs-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">Apostas</div>
                        <div class="panel-body text-center">
                            <h1><?php echo $this->apostas->count(); ?></h1>
                            <h4><?php echo $this->currency($this->montante_apostas); ?></h4>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="row">
                <!-- FINANCEIRO -->
                <div class="col-xs-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">Financeiro</div>
                        <div class="panel-body text-center">
                            <div class="row">
                                <div class="col-xs-6">
                                    <p>Depóstios</p>
                                    <h4><?php echo $this->currency($this->depositos); ?></h4>
                                    <p class="text-muted">Previsto: <?php echo $this->currency($this->depositos_previsto); ?></p>
                                </div>
                                <div class="col-xs-6">
                                    <p>Resgates</p>
                                    <h4 class="text-danger"><?php echo $this->currency($this->resgates); ?></h4>
                                    <p class="text-muted">Previsto: <?php echo $this->currency($this->resgates_previsto); ?></p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12 <?php echo $this->saldo_financeiro < 0 ? 'text-danger' : ''; ?>">
                                    <h2 class="<?php echo $this->saldo_financeiro < 0 ? 'text-danger' : ''; ?>">
                                        <?php echo $this->currency($this->saldo_financeiro); ?>                                        
                                    </h2>
                                    <p class="text-muted">Previsto: <?php echo $this->currency($this->saldo_financeiro_previsto); ?></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <!-- PREMIACOES -->
        <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
            <div class="panel panel-default">
                <div class="panel-heading">Premiações</div>
                <div class="panel-body text-center">
                    <p>1º Prêmio</p>
                    <h4><?php echo $this->currency($this->premio1); ?></h4>
                    <p class="small text-muted">
                        <span><?php echo $this->total_apostas_premio1; ?> apostas</span>
                        <span> - <?php echo $this->porc_premio1; ?>%</span>
                    </p>
                    <hr />
                    <p>2º Prêmio</p>
                    <h4><?php echo $this->currency($this->premio2); ?></h4>
                    <p class="small text-muted">
                        <span><?php echo $this->total_apostas_premio2; ?> apostas</span> 
                        <span> - <?php echo $this->porc_premio2; ?>%</span>
                    </p>
                    <hr />
                    <p>3º Prêmio</p>
                    <h4><?php echo $this->currency($this->premio3); ?></h4>
                    <p class="small text-muted">
                        <span><?php echo $this->total_apostas_premio3; ?> apostas</span> 
                        <span> - <?php echo $this->porc_premio3; ?>%</span>
                    </p>
                    <hr />
                    <h2><?php echo $this->currency($this->premio_total); ?></h2>   
                    <p class="small text-muted">
                        <span><?php echo $this->total_apostas_premio; ?> apostas</span>
                    </p>
                </div>
            </div>
        </div>
        
        <!-- MAIORES VENCEDORES -->
        <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
            <div class="panel panel-default">
                <div class="panel-heading">Maiores Vencedores</div>
                <div class="panel-body">
                    <?php if ($this->apostasVencedoras->count() > 0) : ?>
                        <?php foreach($this->apostasVencedoras as $key => $apostaVencedora) : ?>
                        <div class="row">
                            <div class="col-lg-8 col-md-6 col-sm-6 col-xs-12">
                                <label>
                                    <span><?php echo ++$key; ?>º - </span>
                                    <?php echo $apostaVencedora->usuario_nome; ?>
                                </label>
                            </div>
                            <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12 text-center">
                                <h5><?php echo $this->currency($apostaVencedora->aposta_total_premio); ?></h5>
                            </div>
                            <div class="col-lg-12"><hr /></div>
                        </div>
                        <?php endforeach; ?>
                    <?php else : ?>
                    <div class="alert alert-warning">Nenhum vencedor</div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
        
    </div>
</section>