<section class="bg-write"> 
    <div class="row">
        <div class="col-md-12">  
              <h3>Atualizar Classificação</h3><hr />
        </div>
    </div>
    
    <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr class="text-center">                                
                            <th>Classificação</th>
                            <th>P</th>
                            <th>J</th>
                            <th>V</th>
                            <th>E</th>
                            <th>D</th>
                            <th>GP</th>
                            <th>GC</th>
                            <th>SG</th>
                            <th>Apr (%)</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="text-center">
                            <td class="text-left">
                                <span>
                                    <img src="<?php echo $this->baseUrl('views/img/times/' . $this->classificacao->time_escudo); ?>" width="25" class="img" />
                                    <?php echo $this->classificacao->time_nome; ?>
                                </span> 
                            </td>
                            <td class="bold"><?php echo $this->classificacao->classificacao_pontos; ?></td>
                            <td><?php echo $this->classificacao->classificacao_jogos; ?></td>
                            <td><?php echo $this->classificacao->classificacao_vitorias; ?></td>
                            <td><?php echo $this->classificacao->classificacao_empates; ?></td>
                            <td><?php echo $this->classificacao->classificacao_derrotas; ?></td>
                            <td><?php echo $this->classificacao->classificacao_golspro; ?></td>
                            <td><?php echo $this->classificacao->classificacao_golscontra; ?></td>
                            <td><?php echo $this->classificacao->classificacao_saldogols; ?></td>
                            <td><?php echo $this->classificacao->classificacao_aprov; ?></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
            <div class="well">
                <form method="post" action="">
                    <div class="form-group">
                        <div class="row">
                            <div class="col-lg-4"><?php echo $this->form->classificacao_complemento_jogos; ?></div>
                            <div class="col-lg-4"><?php echo $this->form->classificacao_complemento_pontos; ?></div>
                            <div class="col-lg-4"><?php echo $this->form->classificacao_complemento_vitorias; ?></div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-lg-4"><?php echo $this->form->classificacao_complemento_empates; ?></div>
                            <div class="col-lg-4"><?php echo $this->form->classificacao_complemento_derrotas; ?></div>
                            <div class="col-lg-4"><?php echo $this->form->classificacao_complemento_golspro; ?></div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-lg-4"><?php echo $this->form->classificacao_complemento_golscontra; ?></div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-lg-12"><?php echo $this->form->submit; ?></div>                      
                        </div>
                    </div>
                    <?php echo $this->form->time_id; ?>
                </form>
            </div>
        </div>
    </div>
    
</section>
    