<?php echo $this->partial("header.phtml"); ?>
<div style="width: 100%">
    <div class="col-lg-12">
        <h3 style="color: #EE1289">Olá <?php echo $this->dados['contato_nome']; ?>,</h3>
        <p>
            Recebemos seu contato com sucesso!<br />
            Em breve retornaremos.
        </p>       
        <p>Aguarde.</p>        
    </div>
</div>
<?php echo $this->partial("footer.phtml"); ?>