<?php echo $this->partial("header.phtml"); ?>
<div style="width: 100%">
    <div class="col-lg-12">
        <p>
            Novo contato enviado:
        </p>       
        <p>
            Nome: <?php echo $this->dados['contato_nome']; ?> <br/>
            Email: <?php echo $this->dados['contato_email']; ?> <br/>
            Assunto: <?php echo $this->dados['contato_assunto']; ?> <br/>
            mensagem: <?php echo $this->dados['contato_mensagem']; ?> <br/>
        </p>        
    </div>
</div>
<?php echo $this->partial("footer.phtml"); ?>