        <hr style="border-color: blue" />
        <p style="font-weight: bold">
            A equipe do BrasileirãoBet agradece!
        </p>
        <p>
            <a href="brasileiraobet.com.br" style="color: #EE1289">brasileiraobet.com.br</a>
        </p>
        <p style="font-size: 10px;">
            <span>E-mail enviado automaticamente. Por favor não responda.</span>
        </p>
   </td>
  </tr>
</table>
</body>
