
<body style="
    font-family: Verdana;
    border-color: #ddd;
    -webkit-box-shadow: 5px 6px 11px 0px rgba(50, 50, 49, 0.5);
    -moz-box-shadow:    5px 6px 11px 0px rgba(50, 50, 49, 0.5);
    box-shadow:         5px 6px 11px 0px rgba(50, 50, 49, 0.5);
">
<table cellpadding="0" cellspacing="0" border="0" style="width: 600px; table-layout: fixed;" align="center">
    <tr>
        <td style="background-color: green; color: #FFF; height: 40px; padding: 0 7px; text-align: center;"><h1>BrasileirãoBet</h1></td>
    </tr>
    <tr>
        <td>    
        


