<?php echo $this->partial("header.phtml"); ?>
<div style="width: 100%">
    <div class="col-lg-12">
        <h3 style="color: #EE1289">Olá Nome,</h3>
        <p>
            Recebemos seu cadastro com sucesso!<br />
            Em breve você receberá informações de como encontrar os melhores 
            salões.
        </p>       
        <p>Aguarde.</p>        
    </div>
</div>
<?php echo $this->partial("footer.phtml"); ?>