<?php echo $this->partial("header.phtml"); ?>
<div style="width: 100%">
    <div class="col-lg-12">
        <h3 style="color: #EE1289">Olá <?php echo $this->usuario_nome; ?>,</h3>
        <p>
            As partidas da rodada #<?php echo $this->partida_rodada; ?>
            já estão abertas para apostas!! Não perca tempo e garanta sua chance!!
        </p>                  
    </div>
</div>
<?php echo $this->partial("footer.phtml"); ?>