<?php echo $this->partial("header.phtml"); ?>
<div style="width: 100%">
    <div class="col-lg-12">
        <h3>Olá <?php echo $this->usuario->usuario_nome; ?>,</h3>
        <p>
           Segue o link para criar uma nova senha de acesso ao sistema.
        </p>       
        <p>
            <a href="<?php echo $this->url; ?>" target="_blank">Clique aqui para criar uma nova senha</a>
        </p>
    </div>
</div>
<?php echo $this->partial("footer.phtml"); ?>