<?php echo $this->partial("header.phtml"); ?>
<div style="width: 100%">
    <div class="col-lg-12">
        <h3 style="color: #EE1289">Olá <?php echo $this->usuario->usuario_nome; ?>,</h3>
        <p>
            Foi lançado um crédito de <?php echo $this->currency($this->lancamento_valor); ?> em sua conta.
        </p>           
        <p>
            <b>Motivo: </b><?php echo $this->lancamento_descricao; ?>
        </p>
    </div>
</div>
<?php echo $this->partial("footer.phtml"); ?>