<section>
    <div class="row">
        <div class="col-md-6 col-md-offset-3 bg-write">  
            <h3>Fazer um depósito</h3>
            <form method="post" action="">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <?php echo $this->formDeposito->deposito_valor; ?>       
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <?php echo $this->formDeposito->usuario_cartao_numero; ?>       
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <?php echo $this->formDeposito->usuario_cartao_codigo; ?>       
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <?php echo $this->formDeposito->usuario_cartao_mes; ?>       
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <?php echo $this->formDeposito->usuario_cartao_ano; ?>       
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <?php echo $this->formDeposito->submit; ?>       
                        </div>
                    </div>
                </div>
            </form>                 
        </div>
    </div>
</section>