<section class="bg-write">
    <div class="row">
        <div class="col-md-12 text-center">
            <h3>Minha Conta</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <?php echo $this->partial('usuario/side-bar.phtml'); ?>
        </div>
        <div class="col-md-6 col-md-offset-1">
            <h4>Meus Dados</h4>
            <?php echo $this->form; ?>
        </div>
    </div>
</section>