<section class="bg-write">
    <div class="row">
        <div class="col-md-12 text-center">
            <h3>Minha Conta</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <?php echo $this->partial('usuario/side-bar.phtml'); ?>
        </div>
        <div class="col-md-8">
            <h4>Meus Depósitos</h4>
            <?php if ($this->depositos->count() > 0) : ?>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th class="col-md-3">Data</th>
                            <th class="col-md-3">Valor</th>
                            <th class="col-md-3">Vencimento</th>
                            <th class="col-md-3">Status</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->depositos as $deposito) : ?>
                        <tr class="text-center">
                            <td><?php echo App_Helper_Date::getDate($deposito->deposito_data); ?></td>
                            <td><?php echo $this->currency($deposito->deposito_valor); ?></td>
                            <td><?php echo App_Helper_Date::getDate($deposito->deposito_vencimento); ?></td>
                            <td><?php echo $deposito->deposito_status; ?></td>
                            <td>
                                
                                <?php if ($deposito->deposito_status === 'Aguardando Pagamento') : ?>
                                <a href="<?php echo $deposito->deposito_url; ?>" target="_blank" class="btn btn-sm btn-primary">2º via boleto</a>
                                <?php endif; ?>
                                
                                <?php if ($deposito->deposito_status === 'Gerar Boleto') : ?>
                                <a href="<?php echo $this->url(array(
                                    'controller' => 'pagamento',
                                    'action' => 'boleto',
                                    'id' => $deposito->deposito_id
                                ), 'default', true); ?>" class="btn btn-sm btn-success">Gerar Boleto</a>
                                <?php endif; ?>
                                
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <?php else : ?>
            <div class="alert alert-warning">Nenhum registro</div>
            <?php endif; ?>
        </div>
    </div>
</section>