<div class="list-group">
    <a href="<?php echo $this->url(array(
        'controller' => 'usuario',
        'action' => 'dados'
    ), 'default', true); ?>" class="list-group-item">Dados Cadastro</a>
    <a href="<?php echo $this->url(array(
        'controller' => 'usuario',
        'action' => 'depositos'
    ), 'default', true); ?>" class="list-group-item">Depósitos</a>
    <a href="<?php echo $this->url(array(
        'controller' => 'usuario',
        'action' => 'resgates'
    ), 'default', true); ?>" class="list-group-item">Resgates</a>
    <a href="<?php echo $this->url(array(
        'controller' => 'usuario',
        'action' => 'premios'
    ), 'default', true); ?>" class="list-group-item">Prêmios</a>
</div>