<div class="container">
    <footer>
        <div id="site-map">
            <div class="row">            
                <div class="col-md-12 text-center">                
                    <p>
                        <?php if (Plugin_Auth::check()) : ?>
                        <a href="<?php echo $this->url(array(
                            'module' => 'site',
                            'controller' => 'resultado',
                            'action' => 'index'
                        ), null, true); ?>">Resultados</a>
                        <a href="<?php echo $this->url(array(
                            'module' => 'site',
                            'controller' => 'indique',
                            'action' => 'index'
                        ), null, true); ?>">Indique um amigo</a>
                        <?php endif; ?>
                        <a href="" data-toggle="modal" data-target="#modal-como-funciona">Como funciona?</a>
                    </p>
                    <p class="small">
                        <a href="" data-toggle="modal" data-target="#modal-politica">Política de Privacidede, Regulamento e Termo de Uso</a>                                                 
                    </p>
                </div>
            </div>
        </div>        
        <div class="row">
            <div class="col-md-12 text-center small">
                <p>© Copyright - BrasileirãoBet - todos os direiros reservados</p>
            </div>                    
        </div>
        <div class="row">
            <div class="col-md-12 text-center small">
                Jogue com responsabilidade. Necessário ser maior de 18 anos.
            </div>                    
        </div>
    </footer>
</div>