<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url(array(
                'module' => 'site',
                'controller' => 'index',
                'action' => 'index'
            ), null, true); ?>">
                BRASILEIRÃOBET
                <!--
                <img src="<?php echo $this->baseUrl('views/img/brasileiraobet3.png'); ?>" class="img img-responsive" />
                -->
            </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">   
            <ul class="nav navbar-nav">
                <li>
                    <a href="<?php echo $this->url(array(
                        'module' => 'site',
                        'controller' => 'index',
                        'action' => 'index'
                    ), null, true); ?>">Partidas</a>
                </li>      
                <li>
                    <a href="<?php echo $this->url(array(
                        'module' => 'site',
                        'controller' => 'contato',
                        'action' => 'index'
                    ), null, true); ?>">Contato</a>
                </li>      
                <!--
                <li>
                    <a href="<?php echo $this->url(array(
                        'module' => 'site',
                        'controller' => 'classificacao',
                        'action' => 'index'
                    ), null, true); ?>">Classificação</a>
                </li>      
                -->
            </ul>   
            
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="" data-toggle="modal" data-target="#modal-como-funciona"> Como Funciona?</a>
                </li>                           
            </ul>  
            
            <?php if (Plugin_Auth::check()) : ?>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="<?php echo $this->url(array(
                        'module' => 'site',
                        'controller' => 'resultado',
                        'action' => 'index'
                    ), null, true); ?>">Resultados</a>
                </li>
                <li>
                    <a href="<?php echo $this->url(array(
                        'module' => 'site',
                        'controller' => 'indique',
                        'action' => 'index'
                    ), null, true); ?>"> Indique um amigo</a>
                </li>                            
            </ul>     
            <?php endif; ?>
            
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

