
<section class="bg-write"> 
    <div class="row">
        <div class="col-md-12 text-center">  
              <h3>Resultados</h3>
        </div>
    </div>
    
    <?php if ($this->parciais->count() > 0) : ?> 
    <div class="row">
        <div class="col-md-12">  
            <div class="panel panel-default">
                <div class="panel-heading">Em andamento</div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table">              
                            <?php foreach ($this->parciais as $parcial) : ?>                         
                            <tr class="text-center">
                                <td class="col-md-2"><?php echo App_Helper_Date::getDate($parcial->partida_data, Zend_Date::DATETIME_SHORT); ?>h</td>
                                <td class="col-md-2">
                                    <img src="<?php echo $this->baseUrl('views/img/times/' . $parcial->time_mandante_escudo); ?>" class="img center-block" />
                                </td>
                                <td class="col-md-1 bolder"><?php echo $parcial->parcial_placar_mandante; ?></td>
                                <td class="col-md-1">X</td>
                                <td class="col-md-1 bolder"><?php echo $parcial->parcial_placar_visitante; ?></td>
                                <td class="col-md-2">
                                    <img src="<?php echo $this->baseUrl('views/img/times/' . $parcial->time_visitante_escudo); ?>" class="img center-block" />
                                </td>

                                <td class="col-md-3">
                                    <!-- APOSTAS REALIZADAS PELO USUARIO NA PARTIDA -->
                                    <?php echo $this->apostas($parcial->partida_id, 'label'); ?>
                                </td>

                            </tr>     
                            <?php endforeach; ?>  
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php endif; ?>
    
    <div class="row">
        
        <!--
        <div class="col-md-4">  
            <div class="panel panel-default">
                <div class="panel-heading">Filtros</div>
                <div class="panel-body"></div>
            </div>
        </div>
        -->
        
        <div class="col-md-12">  
            <div class="panel panel-default">
                <div class="panel-heading">Finalizadas</div>
                <div class="panel-body">
                    
                    <div class="table-responsive">
                        <?php if ($this->partidas->count() > 0) : ?>            
                        <h4><?php echo $this->partidas->count(); ?> partidas</h4>
                        <table class="table">
                            <?php foreach ($this->partidas as $partida) : ?>                
                            <tr class="text-center">
                                <td class="col-md-2"><?php echo $partida->partida_serie == 1 ? 'Série A' : 'Série B'; ?></td>
                                <td class="col-md-1"><?php echo $partida->partida_rodada; ?>ª rodada</td>
                                <td class="col-md-2"><?php echo App_Helper_Date::getDate($partida->partida_data, Zend_Date::DATETIME_MEDIUM); ?></td>
                                <td class="col-md-1">
                                    <img src="<?php echo $this->baseUrl('views/img/times/' . $partida->time_mandante_escudo); ?>" class="img center-block" width="40" />
                                </td>
                                <td class="col-md-1"><?php echo $partida->partida_placar_mandante; ?></td>
                                <td class="col-md-1">X</td>
                                <td class="col-md-1"><?php echo $partida->partida_placar_visitante; ?></td>
                                <td class="col-md-1">
                                    <img src="<?php echo $this->baseUrl('views/img/times/' . $partida->time_visitante_escudo); ?>" class="img center-block" width="40" />
                                </td>
                                <td class="col-md-2">                                            
                                    <?php if ($partida->partida_processada) : ?>
                                    <a href="" data-toggle="modal" data-target="#modal-dados-<?php echo $partida->partida_id; ?>" class="btn btn-info">Ver Resultados</a>
                                    <?php else : ?>
                                    Aguardando processamento
                                    <?php endif; ?>
                                </td>
                                <!-- MODAL DE APOSTA -->
                                <div class="modal fade" id="modal-dados-<?php echo $partida->partida_id; ?>" tabindex="-1" role="dialog">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                                <h4 class="modal-title">
                                                    Resultado
                                                </h4>
                                            </div>
                                            <div class="modal-body">

                                                <div class="row">
                                                    <div class="col-lg-12">
                                                        <?php echo $this->apostas($partida->partida_id, 'label'); ?>
                                                        <hr />
                                                    </div>
                                                </div>                                                
                                                
                                                <div class="row">
                                                    <?php if ($partida->partida_valor_premio1) : ?>
                                                    <div class="col-lg-4">
                                                        <div class="well text-center">
                                                            <h4>1º Prêmio:</h4>
                                                            <b>
                                                                <?php echo $this->currency($partida->partida_valor_premio1); ?> <br />
                                                                <?php echo $partida->partida_vencedores_premio1; ?> vencedores <br /> 
                                                                <?php if ($partida->partida_vencedores_premio1 > 0) : ?>
                                                                    <?php echo $this->currency($partida->partida_valor_premio1 / $partida->partida_vencedores_premio1); ?> p/ cada
                                                                <?php endif; ?>
                                                            </b>
                                                        </div>
                                                    </div>
                                                    <?php endif; ?>

                                                    <?php if ($partida->partida_valor_premio2) : ?>
                                                    <div class="col-lg-4">
                                                        <div class="well text-center">
                                                            <h4>2º Prêmio:</h4>
                                                            <b>
                                                                <?php echo $this->currency($partida->partida_valor_premio2); ?> <br />
                                                                <?php echo $partida->partida_vencedores_premio2; ?> vencedores <br /> 
                                                                <?php if ($partida->partida_vencedores_premio2 > 0) : ?>
                                                                    <?php echo $this->currency($partida->partida_valor_premio2 / $partida->partida_vencedores_premio2); ?> p/ cada
                                                                <?php endif; ?>
                                                            </b>
                                                        </div>
                                                    </div>
                                                    <?php endif; ?>

                                                    <?php if ($partida->partida_valor_premio3) : ?>
                                                    <div class="col-lg-4">
                                                        <div class="well text-center">
                                                            <h4>3º Prêmio:</h4>
                                                            <b>
                                                                <?php echo $this->currency($partida->partida_valor_premio3); ?> <br />
                                                                <?php echo $partida->partida_vencedores_premio3; ?> vencedores <br />  
                                                                <?php if ($partida->partida_vencedores_premio3 > 0) : ?>
                                                                    <?php echo $this->currency($partida->partida_valor_premio3 / $partida->partida_vencedores_premio3); ?> p/ cada
                                                                <?php endif; ?>
                                                            </b>
                                                        </div>
                                                    </div>
                                                    <?php endif; ?>

                                                </div>

                                            </div>                            
                                        </div><!-- /.modal-content -->
                                    </div><!-- /.modal-dialog -->
                                </div><!-- /.modal -->                
                            </tr>
                            <?php endforeach; ?>
                        </table>
                        <?php else : ?>
                        <div class="alert alert-warning">Nenhuma partida</div>
                        <?php endif; ?>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
    
</section>