<section class="bg-write">
    <div class="row">
        <div class="col-md-12 text-center">
            <h1>Ops!</h1>
            <p>Desculpe houve um problema. Já estamos verificando.</p>
            <p>Por favor tente novamente mais tarde</p>
        </div>
        <div class="col-md-12">
            <?php if (isset($this->exception)): ?>

                <h3>Exception information:</h3>
                <p>
                    <b>Message:</b> <?php echo $this->exception->getMessage() ?>
                </p>

                <h3>Stack trace:</h3>
                <pre><?php echo $this->exception->getTraceAsString() ?>
                </pre>

                <h3>Request Parameters:</h3>
                <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
                </pre>

            <?php endif ?>
        </div>
    </div>
</section>