<?php echo $this->doctype(); ?>

<html lang="en">
    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Brasileirão Bet</title>

        <!-- CSS -->
        <link href="<?php echo $this->baseUrl("views/css/bootstrap.min.css"); ?>" rel="stylesheet">        
        <link href="<?php echo $this->baseUrl("views/css/bootstrap-theme.min.css"); ?>" rel="stylesheet">
        <!-- Custom Fonts -->
        <link href="<?php echo $this->baseUrl("views/css/font-awesome.min.css"); ?>" rel="stylesheet" type="text/css">
        <link href="<?php echo $this->baseUrl("views/css/style.css"); ?>" rel="stylesheet">
        <link href="<?php echo $this->baseUrl("views/css/site.css"); ?>" rel="stylesheet">

        <!-- Js -->
        <script src="<?php echo $this->baseUrl("views/js/jquery.min.js"); ?>"></script>
        <script src="<?php echo $this->baseUrl("views/js/bootstrap.min.js"); ?>"></script>
        <script src="<?php echo $this->baseUrl("views/js/jquery.maskMoney.js"); ?>"></script>
        <script src="<?php echo $this->baseUrl("views/js/jquery.maskedinput.js"); ?>"></script>
        <script src="<?php echo $this->baseUrl("views/js/application.js"); ?>"></script>

        <?php echo $this->headScript(); ?>

    </head>
    <body>
        
        <!-- message (modal) -->
        <?php echo $this->partial('partials/messages.phtml', array(
            'has_message' => $this->has_message,
            'messages' => $this->messages
        )); ?>
        
        <!-- header -->        
        <?php echo $this->partial('partials/header.phtml'); ?>
        
        <!-- container -->
        <div class="container" id="content">            
            <?php echo $this->layout()->content; ?>                   
        </div> <!-- /container -->        
        
        <!-- footer -->
        <?php echo $this->partial('partials/footer.phtml'); ?>
        
        <!-- politica de privacidade -->
        <?php echo $this->partial('partials/politica.phtml'); ?>
        
        <!-- politica de privacidade -->
        <?php echo $this->partial('partials/como-funciona.phtml'); ?>
        
        <?php echo $this->inlineScript() ?>
    </body>
</html>
