<section>
    <div class="row">
        <div class="col-md-6 col-md-offset-3 bg-write">  
            <h3>Faça seu cadastro e ganhe <label class="text-success"><?php echo $this->currency(Zend_Registry::get("config")->bonus->cadastro); ?> de BÔNUS</label></h3>
            <?php echo $this->formCadastro; ?>
            <p class="small">Ao se cadastrar você concorda com a nossa Política de Privacidede, Regulamento e Termo de Uso</p>
        </div>
    </div>
</section>