<section>
    <div class="row">
        <div class="col-md-12">
            <h3>Adicionar Crédito</h3><hr />
        </div>
    </div>        
    <div class="row">
        <div class="col-md-12">
            <p><b>Usuário: </b><?php echo $this->usuario->usuario_nome; ?></p>
            <p><b>Saldo: </b><?php echo $this->currency($this->usuario->usuario_saldo); ?></p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <?php echo $this->form; ?>
        </div>
    </div>
</section>
    